"use client";

import { useRef } from "react";
import { motion, useInView } from "motion/react";
import { Sparkles, Palette, Calendar } from "lucide-react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { ASSETS } from "@/lib/constants";
import { AnimatedBackground } from "@/components/under-construction/AnimatedBackground";

export function HeroSection() {
  const containerRef = useRef<HTMLDivElement>(null);
  const leftContentRef = useRef<HTMLDivElement>(null);
  const rightContentRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Use Motion's useInView for scroll-triggered animations
  const leftInView = useInView(leftContentRef, { once: true, amount: 0.3 });
  const rightInView = useInView(rightContentRef, { once: true, amount: 0.3 });

  return (
    <section
      ref={containerRef}
      className="relative w-full overflow-hidden bg-background"
    >
      <AnimatedBackground />
      <div className="relative z-10 container mx-auto px-4 sm:px-6 lg:px-8 py-8 lg:py-16">
        <div className="grid lg:grid-cols-2 gap-8 lg:gap-12 items-stretch">
          {/* Left Content */}
          <div ref={leftContentRef} className="space-y-8 flex flex-col">
            {/* Main Headline */}
            <motion.h1
              initial={{ opacity: 0, y: 30 }}
              animate={
                leftInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }
              }
              transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
              className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-foreground leading-tight"
            >
              Transform your wardrobe with AI-powered style guidance
            </motion.h1>

            {/* Description */}
            <motion.p
              initial={{ opacity: 0, y: 30 }}
              animate={
                leftInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }
              }
              transition={{
                duration: 0.8,
                delay: 0.15,
                ease: [0.16, 1, 0.3, 1],
              }}
              className="text-lg sm:text-xl text-muted-foreground leading-relaxed"
            >
              Upload your clothes and let AI analyze and enhance them. Mix and
              match fashion items based on occasion, weather, and your preferred
              style. Join Clamby today and discover your perfect wardrobe.
            </motion.p>

            {/* Feature List */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={
                leftInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }
              }
              transition={{
                duration: 0.8,
                delay: 0.3,
                ease: [0.16, 1, 0.3, 1],
              }}
              className="space-y-4 pt-4"
            >
              <div className="flex items-start gap-4">
                <div className="mt-1 shrink-0">
                  <Sparkles className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <p className="text-base sm:text-lg text-foreground">
                    <span className="font-semibold">AI-powered analysis</span> –
                    Upload your clothes and get polished, enhanced versions
                    generated by AI.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="mt-1 shrink-0">
                  <Palette className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <p className="text-base sm:text-lg text-foreground">
                    <span className="font-semibold">Smart mix & match</span> –
                    Create perfect outfits based on occasion, weather, and your
                    personal style preferences.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="mt-1 shrink-0">
                  <Calendar className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <p className="text-base sm:text-lg text-foreground">
                    <span className="font-semibold">Organized wardrobe</span> –
                    Keep track of all your clothes in one digital space. Never
                    wonder what to wear again.
                  </p>
                </div>
              </div>
            </motion.div>

            {/* App Download Section */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={
                leftInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }
              }
              transition={{
                duration: 0.8,
                delay: 0.45,
                ease: [0.16, 1, 0.3, 1],
              }}
              className="flex flex-col sm:flex-row items-center sm:items-stretch sm:justify-center lg:justify-start gap-6 pt-4"
            >
              {/* QR Code */}
              <div className="hidden sm:flex shrink-0">
                <Image
                  src={ASSETS.QR_CODE}
                  alt="QR Code - Scan to download Clamby app"
                  width={120}
                  height={120}
                  className="w-auto h-auto object-contain rounded-lg"
                />
              </div>

              {/* App Store Buttons */}
              <div className="flex flex-col gap-3 w-full sm:w-auto h-full justify-center">
                <Button
                  size="lg"
                  variant="secondary"
                  className="w-full sm:w-auto bg-foreground text-background hover:bg-foreground/90 h-12 px-8 text-base flex items-center gap-3"
                  disabled
                >
                  <Image
                    src={ASSETS.APP_STORE_BADGE}
                    alt=""
                    width={20}
                    height={20}
                    className="h-6 w-auto"
                  />
                  App Store
                </Button>

                <p className="text-sm text-muted-foreground text-center">
                  Requires iOS 16 and above
                </p>

                {/* Not available for Android yet */}
                {/* <Button
                  size="lg"
                  variant="outline"
                  className="w-full sm:w-auto h-12 px-8 text-base flex items-center gap-3"
                  disabled
                >
                  <Image
                    src={ASSETS.GOOGLE_PLAY_BADGE}
                    alt=""
                    width={20}
                    height={20}
                    className="h-6 w-auto"
                  />
                  Google Play
                </Button> */}
              </div>
            </motion.div>
          </div>

          {/* Right Content - Hero Video */}
          <motion.div
            ref={rightContentRef}
            initial={{ opacity: 0, scale: 0.95 }}
            animate={
              rightInView
                ? { opacity: 1, scale: 1 }
                : { opacity: 0, scale: 0.95 }
            }
            transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
            className="relative h-full"
          >
            <div className="relative h-full w-full rounded-lg overflow-hidden">
              <video
                ref={videoRef}
                src={ASSETS.PLACEHOLDER_VIDEO}
                autoPlay
                loop
                muted
                playsInline
                className="w-full h-full object-cover"
                aria-label="Clamby - Digital Wardrobe Assistant"
              />
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
